### ISSUE TITLE
autocomplete doesn't works properly while deletion and for non selected command.

### ISSUE THREAD

**Issue by zigmos** [subho007/dotzsh#6]
~/.zprezto ❯❯❯ cat modules/syntax-highlighting/external/INSTALL.md                                                              master
cat: modules/syntax-highlighting/external/INST: No such file or directory

**Comment by subho007** [comment]
@zigmos did you try to press the "right" key to complete the autocomplete ?

**Comment by zigmos** [comment]
@subho007  it works by pressing right key, but when u delete, you can't then characters won't be deleted. 
Like in above snippet as you can see, even though, I have deleted everything after 'T' of install, still its visible and as a result of pressing enter it gives no such file or dir.

**Comment by subho007** [comment]
@zigmos you still need to press the right arrow again before you press enter

**Comment by subho007** [comment]
@zigmos closing this, since this is not an issue
